### ISSUE TITLE
Dimensions won't appear

### ISSUE THREAD

**Issue by maos999** [promitor/docs#61]
Hi, 

When trying to add dimensions to my scraper config I don't see any labels or metrics of the dimensions. I only see the metrics from "BackendResponseStatus"
Is their any misunderstanding from my part of how to use dimension? or is there any other error? 

config: 
```
  - name: azure_application_gateway_backend_response_status
    description: "The backend response status from the application gateway"
    resourceType: ApplicationGateway
    labels:
      app: promitor
      resource: applicationgateway
    scraping:
      schedule: "0 */5 * * * *"
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      dimensions: 
        - name: HttpStatus
      aggregation:
        type: Total
        interval: 00:05:00
    resourceDiscoveryGroups:
      - name: application-gateways
```
